var gp_editor=false;function GetCoords(k){var f,e=false,i={};i.h=k.outerHeight();f=k.children(":visible").not(".gplinks");f.length<=1&&(f=k);var j,b,a;f.each(function(d,g){g=$(g);e=g.offset();if(d===0)j=e.top,a=e.left,b=e.left+g.outerWidth();else{if(e.top<j)j=e.top;if(e.left<a)a=e.left;e.left+g.outerWidth()>b&&(b=e.left+g.outerWidth())}});i.w=b-a;i.left=a;i.top=j;return i}
function GetCoords_old(k){var f,e=false,i={};i.h=k.outerHeight(true);if(k.hasClass("editable_area")&&(f=k.children().not(".gplinks"),f.length==1))f=f.eq(0),e=f.offset(),i.w=f.outerWidth(true);if(e===false||e===null)e=k.offset(),i.w=k.outerWidth(true);i.left=e.left;i.top=e.top;return i}
$(function(){function k(){gplinks.gp_refresh=function(b,a){a.preventDefault();window.location=strip_from(window.location.href,"#")};gplinks.toggle_panel=function(b,a){var d=$("#simplepanel");a.preventDefault();var g="keep_viewable";d.hasClass("compact")?d.hasClass("min")?c=0:(c=2,g+=" compact min"):(g+=" compact",c=1);d.attr("class",g);gpui.cmpct=c;$gp.SaveGPUI()};gplinks.toplink=function(b,a){a.preventDefault();if(!$("#simplepanel").hasClass("compact")){var d=$(this).next();gpui[b]=d.is(":visible")?
false:true;$gp.SaveGPUI();d.slideToggle(300)}};gplinks.collapsible=function(b,a){a.preventDefault();var d=$(this).parent();d.hasClass("one")&&d.hasClass("hidden")?(d.parent().find(".head").addClass("hidden"),d.parent().find(".collapsearea").slideUp(300),d.removeClass("hidden").next().slideDown(300)):d.toggleClass("hidden").next().slideToggle(300)};$gp.AdminBox=function(b,a){a.preventDefault();loading();href=jPrep(this.href,"gpreq=flush");$.get(href,"",function(a){$gp.AdminBoxC(a);loaded()},"html")};
gplinks.ajax_box=gplinks.admin_box=$gp.AdminBox;$gp.AdminBoxC=function(b,a){var d=$(window),g=d.width(),d=d.scrollTop(),g=Math.round((g-740)/2),a=a||"",e=Math.max($(document).height(),j.outerHeight(true));$gp.div("gp_admin_box1").css({zIndex:11E3,"min-height":e}).stop(true,true).fadeTo(0,0).fadeTo(200,0.2);d=$gp.div("gp_admin_box").css({zIndex:"11001",left:g,top:d}).stop(true,true).fadeIn(400).html('<a href="#" class="gp_admin_box_close" name="admin_box_close"></a>');$('<div id="gp_admin_boxc" class="'+
a+'"></div>').html(b).appendTo(d);$(".messages").detach()};$gp.CloseAdminBox=function(b,a){a&&a.preventDefault();$("#gp_admin_box1").fadeOut();$("#gp_admin_box").fadeOut(300,function(){$("#gp_admin_boxc").hasClass("inline")?$("#gp_admin_boxc").children().appendTo("#gp_hidden"):$("#gp_admin_boxc").children().remove()});$.fn.colorbox.close()};gplinks.admin_box_close=gpinputs.admin_box_close=$gp.CloseAdminBox;gplinks.remote=function(b,a){a.preventDefault();var d=strip_from(window.location.href,"#"),
g=jPrep(this.href,"gpreq=body");gpRem&&(g+="&in="+encodeURIComponent(d)+"&blink="+encodeURIComponent(gpBLink));d=$(window).height()-130;$gp.AdminBoxC('<iframe src="'+g+'" style="height:'+d+'px;" frameborder="0" />',"iframe")};gpinputs.gpcheck=function(){this.checked?$(this).parent().addClass("checked"):$(this).parent().removeClass("checked")};gpinputs.check_all=function(){$(this).closest("form").find("input[type=checkbox]").prop("checked",this.checked)};$gp.SaveGPUI=function(){l="cmd=savegpui";$.each(gpui,
function(b,a){l+="&gpui_"+b+"="+a});$gp.postC(window.location.href,l)}}function f(){if(!gpui.edb)var b=Math.max($(document).height(),j.outerHeight(true)),a=$gp.div("editable_bar").height(b).bind("mouseenter.edb",function(){var b=0,g=0,e=[],q;q=$gp.div("gp_edit_box");a.html("");$("a.ExtraEditLink").clone(false).attr("class","editable_mark").css({right:0}).show().each(function(p,m){var h;h=0;var o,n,f=false;o=$(m);var i=o.attr("id").substr(13);n=$("#ExtraEditArea"+i);if(n.hasClass("gp_no_overlay"))return true;
if(n.length==0)return true;h=m.title.replace(/_/g," ");h=decodeURIComponent(h);h.length>15&&(h=h.substr(0,14)+"...");o.attr("id","editable_mark"+i).text(h).appendTo(a);h=o.outerWidth();g<h&&(g=h);f=f||o.outerHeight()||24;h=n.offset().top;for(h=Math.max(1,Math.floor(h/f))*f;typeof e[h]!="undefined";)h+=f;e[h]=true;o.css({top:h,left:0}).hover(function(){n.offset().left+n.width()-20<a.width()&&a.fadeTo("slow",0.5);var b=GetCoords(n);q.stop(true,true).css({top:b.top-3,left:b.left-2,width:b.w+4,height:b.h+
5}).fadeIn()},function(){q.stop(true,true).fadeOut();a.fadeTo("fast",1)}).click(function(){$(this).unbind("mouseenter");window.setTimeout(function(){$(this).remove();q.hide()},100)});b++});b<1||a.stop(true).fadeTo("fast",1).animate({left:Math.min(0,g-200)})}).bind("mouseleave.edb",function(){a.stop(true).fadeTo("fast",1).animate({left:-192},1300)})}function e(){function b(a){a&&(a.hasClass("gp_editing")||a.removeClass("gp_no_overlay"))}function a(){if(m){var a=m.offset(),b=m.position(),d=$(window).scrollTop(),
a=Math.max(0,d-(a.top-b.top));m.stop(true,true).animate({top:a})}}function d(){f&&window.clearTimeout(f);f=window.setTimeout(function(){g()},200)}function g(){h=false;p.find("span").stop(true).hide(500);var a=p.find("div");a.stop(true).animate({width:0,height:0},{complete:function(){a.hide()}})}function e(b){var d,h,g;b.hasClass("gp_no_overlay")||(d=b.attr("id").substr(13),h=b.offset(),g=b.outerWidth(true),p.show().css({top:h.top-3,left:h.left-2,width:g+6}),m&&m.remove(),m=$("#ExtraEditLnks"+d).clone(true),
m.length==0&&(d=$("#ExtraEditLink"+d).clone(true),m=$("<span>").append(d)),m.show().find("a").removeClass("ExtraEditLink").first().show(),m.prepend('<a href="#" class="gp_overlay_expand" name="gp_overlay_close"></a>'),p.html("<div></div>").append(m),a(),m.bind("mouseenter",function(){if(!b.hasClass("gp_no_overlay")){$(this).stop(true,true).show().children().show(500).filter(".gp_overlay_expand").attr("class","gp_overlay_close");var a=p.find("div"),d=GetCoords(b);a.stop(true,true).show().animate({width:d.w+
4,height:d.h+5})}}))}var f=false,p,m=false,h;p=$gp.div("gp_edit_overlay");p.bind("click",function(a){var b=$(a.target);b.filter("a").length>0&&(b.attr("name")=="gp_overlay_close"&&a.preventDefault(),h&&h.addClass("gp_no_overlay"));g()}).bind("mouseleave",function(){d()}).bind("mouseenter",function(){f&&window.clearTimeout(f)});$(".editable_area").bind("mousemove.gp mouseenter.gp",function(a){f&&window.clearTimeout(f);var d=$(this);d.parent().closest(".editable_area").length>0&&a.stopPropagation();
h&&d.attr("id")==h.attr("id")||(h&&b(h),h=d,e(h))}).bind("mouseleave",function(){d();b(h)});$(window).scroll(function(){a()})}function i(){SimpleDrag("#simplepanel .toolbar, #simplepanel .toolbar a","#simplepanel","fixed",function(b){gpui.tx=b.left;gpui.ty=b.top;$gp.SaveGPUI()},true);SimpleResize("#admincontainer",{min_w:300,finish:function(b,a){gpui.pposx=a;gpui.pw=b;$gp.SaveGPUI()}});$(".in_window").parent().bind("mouseenter",function(){var b=$(this).children(".in_window").css({right:"auto",left:"100%",
top:0});window.setTimeout(function(){var a=b.offset(),d=a.left+b.width(),a=a.top+b.height(),g=$(window);d>g.width()+g.scrollLeft()&&b.css({right:"100%",left:"auto"});d=g.height()+g.scrollTop();a>d&&b.css({top:d+-a-10})},1)})}$gp.div=function(b){var a=$("#"+b);a.length==0&&(a=$('<div id="'+b+'"></div>').appendTo("#gp_admin_html"));return a};if(isadmin){var j=$("body");$("#gp_admin_html").prependTo(j).size()==0&&j.prepend('<div id="gp_admin_html"></div>');typeof gp_bodyashtml!="undefined"?k():(function(){function b(a){var b,
e,h;h=gpui.pw;h<300&&(h=g.width()-10);b=gpui.pposy;e=gpui.pposx;if(gpui.pdock||b==0&&e==0)e=g.offset(),b=e.top+5,e=e.left+5;d.css({left:Math.max(10,e),top:Math.max(10,b),width:h});gpui.dlayout?gpui.pdock?d.addClass("docked"):d.removeClass("docked"):d.addClass("dlayout");a&&$gp.SaveGPUI()}var a,d,g;a=$("#admincontent");if(!(a.length<1)){g=a.parent().parent();d=a.parent().wrap('<div id="admincontainer" class="gp_floating_area"></div>').parent().appendTo("#gp_admin_html");if(!gpui.dlayout){a=g.offset();
var e=g.width();gpui.pposx=a.left+(e-500)/2;gpui.pposy=a.top+60;gpui.pw=500;gpui.pdock=false}$("#gpAfterContent").css("margin-top",d.height()+100);b(false);SimpleDrag("#admincontent_panel",d,"absolute",function(a){gpui.pposx=a.left;gpui.pposy=a.top;gpui.pdock=false;b(true)});gplinks.gp_docklink=function(a,d){d.preventDefault();gpui.pdock=!gpui.pdock;b(true)}}}(),k(),j.addClass("gpAdmin").trigger("AdminReady"),window.setTimeout(function(){f();e();i();var b=(new Date).getTime();$('<link rel="stylesheet" type="text/css" />').appendTo("head").attr({href:gpBase+
"/include/thirdparty/jquery_ui/jquery-ui-1.8.7.custom.css?t="+b}).clone().appendTo("head").attr({href:gpBase+"/include/css/inline_edit.css?t="+b})},500),window.setInterval(function(){if(!gpui.edb){var b=Math.max($(document).height(),j.outerHeight(true));$("#editable_bar").height(b)}},5E3),window.onbeforeunload=function(){if(gp_editor&&typeof gp_editor.checkDirty!="undefined"&&gp_editor.checkDirty())return"Unsaved changes will be lost."},gplinks.inline_edit_generic=function(b,a){a.preventDefault();
loading();if(typeof gplinks[b]=="function")gplinks[b].call(this,b,a);else{var d=strip_from(this.href,"#"),g=$(this).attr("id").substr(13);script=d+"&cmd=inlineedit&area_id="+g;$.getScript(script,function(a){a=="false"&&(alert(gp_error),loaded())})}},$gp.InlineStyles=function(){},$gp.Loaded={},$gp.LoadScripts=function(b,a,d){function g(){e--;e==0&&typeof a=="function"&&a.call(this)}var e=b.length,f=(new Date).getTime(),i="";d&&(i=gpBase);$.each(b,function(a,b){b=i+b;$gp.Loaded[b]?g():($gp.Loaded[b]=
true,$.getScript(jPrep(b,"t="+f),function(){g()}))})},$gp.htmlchars=function(b){return b.replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/'/g,"&#039;").replace(/</g,"&lt;").replace(/>/g,"&gt;")})}});
function SimpleDrag(k,f,e,i){function j(a,g){if(a.css("position")=="fixed"){var e=a.data("gp_left"),f=a.data("gp_top");e&&a.css({left:e,top:f});var e=a.offset(),f=a.width(),h=a.height();g&&a.data({gp_left:e.left,gp_top:e.top});h=d.height()+d.scrollTop()-h-b;e.top<b?a.css({top:b}):e.top>h&&a.css({top:h});f=d.width()+d.scrollLeft()-f-b;e.left>f&&a.css({left:f})}}var b=-10,a=$(f).addClass("keep_viewable"),d=$(window),g=$(document);$(k).die("mousedown.sdrag").live("mousedown.sdrag",function(f){var j,
k,m;f.preventDefault();if(!(a.length<1))return function(){var b=a.offset();k=f.clientX-b.left+d.scrollLeft();m=f.clientY-b.top+d.scrollTop()}(),g.bind("mousemove.sdrag",function(d){if(!j){var e=a.offset(),g=a.width(),f=a.height();j=$gp.div("admin_drag_box").css({top:e.top,left:e.left,width:g,height:f})}j.css({left:Math.max(b,d.clientX-k),top:Math.max(b,d.clientY-m)});d.preventDefault();return false}),g.unbind("mouseup.sdrag").bind("mouseup.sdrag",function(f){var o,n,r;g.unbind("mousemove.sdrag mouseup.sdrag");
if(!j)return false;f.preventDefault();j.remove();j=false;o=f.clientX-k;n=f.clientY-m;e=="absolute"&&(o+=d.scrollLeft(),n+=d.scrollTop());o=Math.max(b,o);n=Math.max(b,n);r={left:o,top:n};a.css(r).data({gp_left:o,gp_top:n});typeof i=="function"&&i.call(a,r,f);return false}),false});j(a,true);d.resize(function(){$(".keep_viewable").each(function(){j($(this),false)})})}
function RenamePrep(){function k(){b.val().replace("_"," ")!=j?$("#gp_rename_redirect").show(500):$("#gp_rename_redirect").hide(300)}function f(a){a.preventDefault();var a=$(this).closest("td"),b=a.find("a:visible");a.find("a").show();b.hide();if(b=a.find("a:visible").get(0))b.className=="slug_edit"?(a.find("input").addClass("sync_label").prop("disabled","disabled").fadeTo(400,0.6),e()):a.find("input").removeClass("sync_label").prop("disabled","").fadeTo(400,1)}function e(){var a;a=$("input.title_label").val();
a=a.replace(/</g," ").replace(/>/g," ").replace(/\//g," ").replace(/\\/g," ").replace(/\|/g," ");a=$.trim(a);a=a.replace(/"/g,"").replace(/'/g,"").replace(/\?/g,"").replace(/#/g,"").replace(/\*/g,"").replace(/:/g,"");a=a.replace(/[\x00-\x1F\x7F]/g,"");$("input.sync_label").val(a);k();return true}var i,j,b;(function(){i=$("#gp_rename_form");j=i.find("input[name=old_title]").val();b=$("input.new_title");e();$("input[disabled=disabled]").each(function(a,b){$(b).fadeTo(400,0.6)});$("input.title_label").bind("keyup change",
e);$(".label_synchronize a").click(f);gplinks.showmore=function(a,b){b.preventDefault();$("#gp_rename_table tr").show(500);$(this).remove()};b.bind("keyup change",function(){k()})})()}
function SimpleResize(k,f){var f=$.extend({},{max_w:1E4,min_w:0,finish:function(){}},f),e=$(k);e.length<1||($handle_areas=$('<span class="gp_admin_resize"></span><span class="gp_admin_resize gp_resize_right"></span>').appendTo(e).bind("mousedown.sres",function(i){var j=i.clientX,b=start_w=e.width(),a=start_l=e.position().left,d=$(this);i.preventDefault();$(document).bind("mousemove.sres",function(g){$("body").disableSelection();g.preventDefault();d.hasClass("gp_resize_right")?b=g.clientX-j+start_w:
(a=g.clientX-j+start_l,b=j-g.clientX+start_w);b=Math.min(f.max_w,b);b=Math.max(f.min_w,b);e.width(b);a=Math.max(0,a);e.css({left:a});return false}).unbind("mouseup.sres").bind("mouseup.sres",function(d){d.preventDefault();$("body").enableSelection();$(document).unbind("mousemove.sres mouseup.sres");f.finish.call(e,b,a);return false});return false}))}$.fn.disableSelection=function(){$(this).attr("unselectable","on").css("-moz-user-select","none").each(function(){this.onselectstart=function(){return false}})};
$.fn.enableSelection=function(){$(this).attr("unselectable","off").css("-moz-user-select","").each(function(){this.onselectstart=function(){return false}})};