var gpPublic,$gp,gp_error="There was an error processing the last request. Please reload this page to continue.",logi=0;function LOG(a){$('<div style="padding:20px" />').html(logi+" :: "+a).appendTo("body");logi++}function LOGO(a){var c="",b;for(b in a)try{try{c+="<br/><b>"+b+"</b> = "+a[b].toString().replace(/</g,"&lt;")+"\n"}catch(e){c+="<br/><b>"+b+"</b> = "+a[b]+"\n"}}catch(g){c+="<br/><b>"+b+"</b> -- not allowed -- \n"}LOG(c)}
function createCookie(a,c,b){if(b){var e=new Date;e.setTime(e.getTime()+b*864E5);b="; expires="+e.toGMTString()}else b="";document.cookie=a+"="+c+b+"; path=/"}function eraseCookie(a){createCookie(a,"",-1)}function jPrep(a,c){c=typeof c=="undefined"?"gpreq=json&jsoncallback=?":c;a=strip_from(a,"#");a+=a.indexOf("?")==-1?"?":"&";return a+c}
function ajaxResponse(a){$(".messages").detach();var c=false;$.each(a,function(b,a){if(typeof gpresponse[a.DO]=="function")gpresponse[a.DO].call(this,a);else switch(a.DO){case "replace":$(a.SELECTOR).replaceWith(a.CONTENT);break;case "inner":$(a.SELECTOR).html(a.CONTENT);break;case "eval":eval(a.CONTENT);break;case "renameprep":RenamePrep();break;case "admin_box_data":c=true;$gp.AdminBoxC(a.CONTENT);break;case "messages":$(a.CONTENT).appendTo("body").show().css({top:0})}});if(!c){try{$gp.CloseAdminBox()}catch(b){}try{$.fn.colorbox.close()}catch(e){}}loaded()}
$(function(){var a="";$("body").addClass(IE7?"IE7CLASS":"STCLASS");eraseCookie("cookie_cmd");gpPublic=$gp=function(){return this};$gp.jGoTo=function(a){loading();a=jPrep(a);$.getJSON(a,ajaxResponse)};$gp.cGoTo=function(a,b){var e;e=b?window.location.href:strip_from(a.href,"?");createCookie("cookie_cmd",encodeURIComponent(a.search+"&verified="+post_nonce),1);window.location=strip_from(e,"#")};$gp.post=function(a){loading();var b=$(a).closest("form"),e=b.serialize()+"&verified="+encodeURIComponent(post_nonce);
a.nodeName=="INPUT"&&(e+="&"+encodeURIComponent(a.name)+"="+encodeURIComponent(a.value));$.post(jPrep(b.attr("action")),e,ajaxResponse,"json");return false};$gp.post_link=function(a){loading();var b=a.search;b[0]=="?"&&(b=b.substring(1));$gp.postC(a.href,b)};$gp.postC=function(a,b,e,g){e=e||ajaxResponse;g=g||"json";typeof b=="object"&&(b=jQuery.param(b,true));b+="&verified="+encodeURIComponent(post_nonce);g=="json"&&(b+="&gpreq=json&jsoncallback=?");$.post(strip_from(a,"?"),b,e,g)};$gp.LiveJQ=function(){};
(function(){function a(b){$(b).filter("[method=post]").append('<input type="hidden" name="verified" value="'+post_nonce+'" />')}function b(a,b){var c=$(a).find("form").get(0);c&&$(b).find("input").each(function(a,b){if(c[b.name])c[b.name].value=b.value})}$(document).ajaxError(function(a,b,c,f){typeof debugjs!=="undefined"?(loaded(),a={thrownError:f,text:b.responseText,status:b.status,statusText:b.statusText,url:c.url,type:c.type,data:c.data.substr(0,100),browser:$.param($.browser)},LOGO(a),alert("Error detected. See bottom of page for details")):
typeof c.error!="function"&&(loaded(),alert(gp_error))});$("form").live("mousedown",function(){$this=$(this);if($this.data("gpForms")!="checked"){if(typeof this["return"]!=="undefined")this["return"].value=window.location;$this.data("gpForms","checked")}});$("input").live("click",function(b){a(this.form);$this=$(this);var g=strip_from($this.attr("class")," ");if(typeof gpinputs[g]=="function")return gpinputs[g].call(this,b,b);switch(g){case "gppost":case "gpajax":return $gp.post(this)}return true});
$("form").live("submit",function(){a(this)});$(".expand_child").live("mouseenter",function(){$(this).addClass("expand");$(this).hasClass("simple_top")&&$(this).addClass("simple_top_hover")}).live("mouseleave",function(){$(this).removeClass("expand").removeClass("simple_top_hover")});$("a[name]").live("click",function(a){var c=$(this),h=c.attr("name"),f=c.attr("rel");if(c.hasClass("gpconfirm")&&(a.preventDefault(),!confirm(this.title)))return;if(typeof gplinks[h]=="function")return gplinks[h].call(this,
f,a);var i={opacity:0.75,maxWidth:"90%",minWidth:300,minHeight:300,maxHeight:"90%"};switch(h){case "tabs":tabs(this);break;case "toggle_show":$(f).toggle();break;case "inline_box":b(f,this);$.fn.colorbox($.extend(i,{inline:true,href:f,open:true}));break;case "iadmin_box":b(f,this);$gp.AdminBoxC($(f),"inline");break;case "postlink":$gp.post_link(this);break;case "gpajax":$gp.jGoTo(this.href);break;case "creq":$gp.cGoTo(this,true);break;case "cnreq":$gp.cGoTo(this,false);break;case "close_message":c=
c.closest("div");h=c.height();c.animate({top:-(h+2)});break;case "gallery":$(f==""?this:"a[rel="+f+"]").colorbox($.extend(i,{resize:true}));$.fn.colorbox.launch(this);break;default:return true}a.preventDefault();return false})})();$("body").trigger("gpReady")});function loading(){$("#loading1").css("zIndex",99E3).fadeTo(1,0.3).next().css("zIndex",99001).show()}function loaded(){$("#loading1, #loading2").clearQueue().hide()}function message(){$("#loading1, #loading2").clearQueue().hide()}
function tabs(a){$(a.parentNode).find("a").removeClass("selected").each(function(a,b){var e=strip_to(b.href,"#");e&&$("#"+e).hide()});d=strip_to(a.href,"#");$("#"+d).show();a.className="selected"}function strip_to(a,c){if(!a)return a;var b=a.indexOf(c);return b>-1?a.substr(b+1):false}function strip_from(a,c){if(!a)return a;var b=a.indexOf(c);b>0&&(a=a.substr(0,b));return a};